server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://server:3000/;  # Прокси на сервер внутри Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ \.js$ {
        add_header Content-Type application/javascript;
    }

    location ~ \.css$ {
        add_header Content-Type text/css;
    }
}