version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/CMD_PRJ  # Подключение к MongoDB
    volumes:
      - ./server:/app  # Монтируем папку server в контейнер
      - /app/node_modules  # Исключаем node_modules из монтирования
    command: npm run dev  # Запуск в режиме разработки
    depends_on:
      - mongo  # Зависимость от MongoDB

  client:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app  # Монтируем папку client в контейнер
      - /app/node_modules  # Исключаем node_modules из монтирования
    command: npm run dev  # Запуск в режиме разработки
    depends_on:
      - server  # Зависимость от сервера

  mongo:
    image: mongo:latest  # Используем официальный образ MongoDB
    container_name: mongo
    ports:
      - "27017:27017"  # Порт для подключения к MongoDB
    volumes:
      - mongo-data:/data/db  # Сохраняем данные MongoDB в volume
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Опционально: имя пользователя
      MONGO_INITDB_ROOT_PASSWORD: example  # Опционально: пароль

volumes:
  mongo-data:  # Volume для хранения данных MongoDB